# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np`

In [ ]:
# prompt:  Import the numpy package under the name

import numpy as np


#### 2. Print the numpy version and the configuration

In [ ]:
# prompt: Print the numpy version and the configuration

import numpy as np

print(np.__version__)
print(np.show_config())


1.25.2
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

#### 3. Create a null vector of size 10

In [ ]:
# prompt: Create a null vector of size 10

import numpy as np

# Create a null vector of size 10
null_vector = np.zeros(10)

print(null_vector)



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array

In [ ]:
# prompt: How to find the memory size of any array

# How to find the memory size of any array

# Create an array
array = np.array([1, 2, 3, 4, 5])

# Find the memory size of the array
memory_size = array.nbytes

# Print the memory size
print(f"Memory size of the array: {memory_size} bytes")


Memory size of the array: 40 bytes


#### 5. How to get the documentation of the numpy add function from the command line?

In [ ]:
# prompt: How to get the documentation of the numpy add function from the command line?

!python -c "import numpy; print(numpy.add.__doc__)"


add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 5. How to get the documentation of the numpy add function from the command line?

#### 6. Create a null vector of size 10 but the fifth value which is 1

In [ ]:
# prompt: Create a null vector of size 10 but the fifth value which is 1

import numpy as np

null_vector = np.zeros(10)
null_vector[4] = 1

print(null_vector)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49

In [ ]:
# prompt: Create a vector with values ranging from 10 to 49

vector = np.arange(10, 50)
print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last)

In [ ]:
# prompt: Reverse a vector (first element becomes last)

vector = np.arange(10, 50)

reversed_vector = vector[::-1]

print(reversed_vector)


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
# prompt: Create a 3x3 matrix with values ranging from 0 to 8

matrix = np.arange(0, 9).reshape(3, 3)
print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [ ]:
# prompt: Find indices of non-zero elements from [1,2,0,0,4,0]

import numpy as np

array = np.array([1, 2, 0, 0, 4, 0])

non_zero_indices = np.nonzero(array)

print(non_zero_indices)


(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix

In [ ]:
# prompt: Create a 3x3 identity matrix

identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [ ]:
# prompt: Create a 3x3x3 array with random values

import numpy as np

# Create a 3x3x3 array with random values
random_array = np.random.rand(3, 3, 3)

print(random_array)


[[[0.28179226 0.42775681 0.95100107]
  [0.81224391 0.92959415 0.79682493]
  [0.25522838 0.15337202 0.35443465]]

 [[0.11613318 0.68797487 0.76301457]
  [0.0469616  0.66050313 0.57770526]
  [0.0100368  0.00545412 0.21700354]]

 [[0.67081377 0.66025188 0.10245957]
  [0.25563968 0.7792935  0.2868969 ]
  [0.46262109 0.20443239 0.06916236]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [ ]:
# prompt: Create a 10x10 array with random values and find the minimum and maximum values

# Create a 10x10 array with random values
array = np.random.rand(10, 10)

# Find the minimum and maximum values
min_value = np.min(array)
max_value = np.max(array)

# Print the minimum and maximum values
print(f"Minimum value: {min_value}")
print(f"Maximum value: {max_value}")


Minimum value: 0.0004754684167888046
Maximum value: 0.993810881602491


#### 14. Create a random vector of size 30 and find the mean value

In [ ]:
# prompt: Create a random vector of size 30 and find the mean value

# Create a random vector of size 30
vector = np.random.rand(30)

# Find the mean value
mean_value = np.mean(vector)

# Print the mean value
print(f"Mean value: {mean_value}")


Mean value: 0.5143652367320954


#### 15. Create a 2d array with 1 on the border and 0 inside

In [ ]:
# prompt: Create a 2d array with 1 on the border and 0 inside

import numpy as np

# Create a 5x5 array with zeros
array = np.zeros((5, 5))

# Set the border elements to 1
array[0, :] = 1
array[-1, :] = 1
array[:, 0] = 1
array[:, -1] = 1

# Print the array
print(array)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
```

#### 16. How to add a border (filled with 0's) around an existing array?

In [ ]:
# prompt: How to add a border (filled with 0's) around an existing array?

import numpy as np

# Create the original array
original_array = np.array([[1, 2, 3],
                          [4, 5, 6],
                          [7, 8, 9]])

# Define the border size
border_size = 1

# Create a new array with the desired size
new_array = np.zeros((original_array.shape[0] + 2 * border_size,
                     original_array.shape[1] + 2 * border_size))

# Copy the original array into the new array
new_array[border_size:-border_size, border_size:-border_size] = original_array

# Print the new array
print(new_array)


[[0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 0.]
 [0. 4. 5. 6. 0.]
 [0. 7. 8. 9. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression?
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
# prompt: What is the result of the following expression?
# 0 * np.nan
# np.nan == np.nan
# np.inf > np.nan
# np.nan - np.nan
# np.nan in set([np.nan])
# 0.3 == 3 * 0.1

print(0 * np.nan)  # Output: nan
print(np.nan == np.nan)  # Output: False
print(np.inf > np.nan)  # Output: False
print(np.nan - np.nan)  # Output: nan
print(np.nan in set([np.nan]))  # Output: True
print(0.3 == 3 * 0.1)  # Output: False


nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [ ]:
# prompt: Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

import numpy as np

# Create a 5x5 matrix filled with zeros
matrix = np.zeros((5, 5))

# Set the values just below the diagonal
matrix[1:, :-1] = np.arange(1, 5)

# Print the matrix
print(matrix)


[[0. 0. 0. 0. 0.]
 [1. 2. 3. 4. 0.]
 [1. 2. 3. 4. 0.]
 [1. 2. 3. 4. 0.]
 [1. 2. 3. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [ ]:
# prompt: Create a 8x8 matrix and fill it with a checkerboard pattern

# Create an 8x8 matrix filled with zeros
checkerboard = np.zeros((8, 8))

# Fill the even rows with alternating 1s and 0s
checkerboard[::2, ::2] = 1
checkerboard[1::2, 1::2] = 1

# Print the checkerboard
print(checkerboard)


[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
# prompt: Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

import numpy as np

# Calculate the index of the 100th element in a (6, 7, 8) shape array
array_shape = (6, 7, 8)
index = np.unravel_index(100, array_shape)

# Print the index
print(index)

# Output: (1, 5, 4)


(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function

In [ ]:
# prompt: Create a checkerboard 8x8 matrix using the tile function

# Create a 2x2 checkerboard pattern
checkerboard_pattern = np.array([[0, 1],
                              [1, 0]])

# Tile the checkerboard pattern to create an 8x8 checkerboard
checkerboard = np.tile(checkerboard_pattern, (4, 4))

# Print the checkerboard
print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix

In [ ]:
# prompt: Normalize a 5x5 random matrix

# Generate a random 5x5 matrix
random_matrix = np.random.rand(5, 5)

# Normalize the matrix
normalized_matrix = (random_matrix - np.min(random_matrix)) / (np.max(random_matrix) - np.min(random_matrix))

# Print the normalized matrix
print(normalized_matrix)


[[0.10835229 0.27205876 0.30032437 0.3519679  0.94035587]
 [0.90951389 0.21593339 0.11233073 0.89447125 0.99685539]
 [0.66235699 0.36261829 0.47142141 0.76118074 0.04504381]
 [0.56174155 0.13582326 0.84146964 0.12630122 0.28685423]
 [0.36876684 0.08261548 1.         0.10106174 0.        ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [ ]:
# prompt: Create a custom dtype that describes a color as four unsigned bytes (RGBA)

import numpy as np

color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [ ]:
# prompt: Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

import numpy as np

# Create a 5x3 matrix
matrix_a = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9],
                     [10, 11, 12],
                     [13, 14, 15]])

# Create a 3x2 matrix
matrix_b = np.array([[1, 2],
                     [3, 4],
                     [5, 6]])

# Multiply the matrices
matrix_product = np.dot(matrix_a, matrix_b)

# Print the matrix product
print(matrix_product)


[[ 22  28]
 [ 49  64]
 [ 76 100]
 [103 136]
 [130 172]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [ ]:
# prompt:  Given a 1D array, negate all elements which are between 3 and 8, in place.

import numpy as np

# Create a 1D array
array = np.arange(11)

# Find the indices of elements between 3 and 8
indices = np.where((array >= 3) & (array <= 8))

# Negate the elements at the specified indices
array[indices] *= -1

# Print the modified array
print(array)


[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script?
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
# prompt: What is the output of the following script?
# # Author: Jake VanderPlas
# print(sum(range(5),-1))
# from numpy import *
# print(sum(range(5),-1))

# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))



9
10


#### 27. Consider an integer vector Z, which of these expressions are legal?
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
# prompt: Consider an integer vector Z, which of these expressions are legal?
# Z**Z
# 2 << Z >> 2
# Z <- Z
# 1j*Z
# Z/1/1
# Z<Z>Z

Z**Z  # Legal
2 << Z >> 2  # Legal
# Z <- Z  # Illegal
1j*Z  # Legal
Z/1/1  # Legal
# Z<Z>Z  # Illegal


NameError: name 'Z' is not defined

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
# prompt: What are the result of the following expressions?
# np.array(0) / np.array(0)
# np.array(0) // np.array(0)
# np.array([np.nan]).astype(int).astype(float)

print(np.array(0) / np.array(0))  # Output: nan
print(np.array(0) // np.array(0))  # Output: 0
print(np.array([np.nan]).astype(int).astype(float))  # Output: [-2.14748365e+09]


nan
0
[-9.22337204e+18]


<ipython-input-27-e6702719d63c>:6: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))  # Output: nan
<ipython-input-27-e6702719d63c>:7: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))  # Output: 0
<ipython-input-27-e6702719d63c>:8: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))  # Output: [-2.14748365e+09]


#### 29. How to round away from zero a float array ?

In [ ]:
# prompt: How to round away from zero a float array ?

array = np.array([1.1, 1.5, -1.1, -1.5])
print(np.trunc(array))


[ 1.  1. -1. -1.]


#### 30. How to find common values between two arrays?

In [ ]:
# prompt: How to find common values between two arrays?

# Create two arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

# Find common values
common_values = np.intersect1d(array1, array2)

# Print the common values
print(common_values)



[3 4 5]


#### 31. How to ignore all numpy warnings (not recommended)?

In [ ]:
# prompt: How to ignore all numpy warnings (not recommended)?

import numpy as np
import warnings

# Ignore all numpy warnings
warnings.filterwarnings("ignore")

# Create an array with invalid values
array = np.array([np.nan, np.inf, -np.inf])

# Print the array without warnings
print(array)


[ nan  inf -inf]


#### 32. Is the following expressions true?
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
# prompt: Is the following expressions true?
# np.sqrt(-1) == np.emath.sqrt(-1)

print(np.sqrt(-1) == np.emath.sqrt(-1))


False


#### 33. How to get the dates of yesterday, today and tomorrow?

In [ ]:
# prompt: How to get the dates of yesterday, today and tomorrow?

import datetime

# Get today's date
today = datetime.date.today()

# Get yesterday's date
yesterday = today - datetime.timedelta(days=1)

# Get tomorrow's date
tomorrow = today + datetime.timedelta(days=1)

# Print the dates
print(f"Yesterday: {yesterday}")
print(f"Today: {today}")
print(f"Tomorrow: {tomorrow}")


Yesterday: 2024-07-04
Today: 2024-07-05
Tomorrow: 2024-07-06


#### 34. How to get all the dates corresponding to the month of July 2016?

In [ ]:
# prompt: How to get all the dates corresponding to the month of July 2016?

import calendar

# Get all the dates in July 2016
dates = calendar.monthcalendar(2016, 7)

# Print the dates
for week in dates:
    for date in week:
        print(date)


0
0
0
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)?

In [ ]:
# prompt: How to compute ((A+B)*(-A/2)) in place (without copy)?

A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(B,A,out=B)


array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods

In [ ]:
# prompt: Extract the integer part of a random array of positive numbers using 4 different methods

# Generate a random array of positive numbers
array = np.random.rand(10) * 100

# Method 1: Using np.floor
integer_part_1 = np.floor(array)

# Method 2: Using np.trunc
integer_part_2 = np.trunc(array)

# Method 3: Using // operator
integer_part_3 = array // 1

# Method 4: Casting to integer type
integer_part_4 = array.astype(int)

# Print the results
print("Original array:", array)
print("Integer part (np.floor):", integer_part_1)
print("Integer part (np.trunc):", integer_part_2)
print("Integer part (// operator):", integer_part_3)
print("Integer part (astype(int)):", integer_part_4)


Original array: [60.07704878 40.20794247 52.30641707 10.92481595 87.81621595  8.3367603
 65.02666532 95.22440371 57.94800879 96.89573627]
Integer part (np.floor): [60. 40. 52. 10. 87.  8. 65. 95. 57. 96.]
Integer part (np.trunc): [60. 40. 52. 10. 87.  8. 65. 95. 57. 96.]
Integer part (// operator): [60. 40. 52. 10. 87.  8. 65. 95. 57. 96.]
Integer part (astype(int)): [60 40 52 10 87  8 65 95 57 96]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4

In [ ]:
# prompt: Create a 5x5 matrix with row values ranging from 0 to 4

import numpy as np

matrix = np.zeros((5, 5))
for i in range(5):
    matrix[i, :] = i

print(matrix)


[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array

In [ ]:
# prompt: Consider a generator function that generates 10 integers and use it to build an array

def generate_integers():
    for i in range(10):
        yield i

# Create an array from the generator function
array = np.fromiter(generate_integers(), dtype=int)

# Print the array
print(array)


[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [ ]:
# prompt: Create a vector of size 10 with values ranging from 0 to 1, both excluded

np.linspace(0, 1, 10, endpoint=False)


array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

#### 40. Create a random vector of size 10 and sort it

In [ ]:
# prompt: Create a random vector of size 10 and sort it

random_vector = np.random.rand(10)
sorted_vector = np.sort(random_vector)

print(sorted_vector)


[0.00981857 0.21809545 0.35603193 0.39503271 0.51759003 0.56944273
 0.78378117 0.88310692 0.93259798 0.98001835]


#### 41. How to sum a small array faster than np.sum?

In [ ]:
# prompt: How to sum a small array faster than np.sum?

def faster_sum(array):
  """
  Sum a small array faster than np.sum.

  Args:
      array: The array to sum.

  Returns:
      The sum of the array.
  """
  sum = 0
  for i in array:
    sum += i
  return sum

array = np.array([1, 2, 3, 4, 5])
print(faster_sum(array))


15


#### 42. Consider two random array A and B, check if they are equal

In [ ]:
# prompt: Consider two random array A and B, check if they are equal

import numpy as np

# Generate two random arrays
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)

# Compare the arrays
equal_arrays = np.array_equal(A, B)

# Print the result
print(f"Are arrays A and B equal? {equal_arrays}")


Are arrays A and B equal? False


#### 43. Make an array immutable (read-only)

In [ ]:
# prompt: Make an array immutable (read-only)

import numpy as np

# Create a random array
array = np.random.rand(3, 3)

# Make the array immutable
array.flags.writeable = False

# Try to modify the array
try:
    array[0, 0] = 1
except ValueError as e:
    print(f"Error: {e}")

# Print the array
print(array)


Error: assignment destination is read-only
[[0.38307269 0.12856439 0.67918941]
 [0.53608224 0.8734126  0.20364492]
 [0.7293701  0.40824654 0.15956692]]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [ ]:
# prompt: Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

# Generate a random 10x2 matrix representing cartesian coordinates
cartesian_coordinates = np.random.rand(10, 2)

# Convert cartesian coordinates to polar coordinates
polar_coordinates = np.sqrt(np.sum(cartesian_coordinates**2, axis=1)).reshape(-1, 1)
polar_coordinates = np.arctan2(cartesian_coordinates[:, 1], cartesian_coordinates[:, 0])

# Print the polar coordinates
print(polar_coordinates)


[0.0975778  0.93283126 0.414908   1.52241897 0.43705118 0.23288085
 0.36752412 1.18709081 0.26628914 1.20339483]


#### 45. Create random vector of size 10 and replace the maximum value by 0

In [ ]:
# prompt: Create random vector of size 10 and replace the maximum value by 0

import numpy as np

# Create random vector of size 10
vector = np.random.rand(10)

# Find the maximum value
max_value = np.max(vector)

# Replace the maximum value with 0
vector[vector == max_value] = 0

# Print the modified vector
print(vector)


[0.2204689  0.33027892 0.03110698 0.66353895 0.24594955 0.54860705
 0.         0.92390986 0.03173946 0.95708642]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area

In [ ]:
# prompt: Create a structured array with x and y coordinates covering the [0,1]x[0,1] area

import numpy as np

# Create a structured array with x and y coordinates
structured_array = np.zeros((10, 10), dtype=[('x', float), ('y', float)])

# Fill the array with x and y coordinates
structured_array['x'] = np.linspace(0, 1, 10)
structured_array['y'] = np.linspace(0, 1, 10)[:, np.newaxis]

# Print the structured array
print(structured_array)


[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [ ]:
# prompt: Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

def cauchy_matrix(X, Y):
  """
  Constructs the Cauchy matrix C (Cij =1/(xi - yj)) given two arrays X and Y.

  Args:
      X: The first array.
      Y: The second array.

  Returns:
      The Cauchy matrix C.
  """

  # Broadcast the arrays to have the same shape
  X, Y = np.broadcast_arrays(X, Y)

  # Calculate the Cauchy matrix
  C = 1 / (X - Y[:, np.newaxis])

  return C

# Example usage
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

C = cauchy_matrix(X, Y)

print(C)


[[-0.33333333 -0.5        -1.        ]
 [-0.25       -0.33333333 -0.5       ]
 [-0.2        -0.25       -0.33333333]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type

In [ ]:
# prompt:  Print the minimum and maximum representable value for each numpy scalar type

for dtype in [np.bool_, np.int8, np.int16, np.int32, np.int64, np.uint8,
                np.uint16, np.uint32, np.uint64, np.float16, np.float32, np.float64]:
    print(f"{dtype.__name__}:")
    print(f"  min: {np.min(np.array([0], dtype=dtype))}")
    print(f"  max: {np.max(np.array([0], dtype=dtype))}")
    print("")


bool_:
  min: False
  max: False

int8:
  min: 0
  max: 0

int16:
  min: 0
  max: 0

int32:
  min: 0
  max: 0

int64:
  min: 0
  max: 0

uint8:
  min: 0
  max: 0

uint16:
  min: 0
  max: 0

uint32:
  min: 0
  max: 0

uint64:
  min: 0
  max: 0

float16:
  min: 0.0
  max: 0.0

float32:
  min: 0.0
  max: 0.0

float64:
  min: 0.0
  max: 0.0



#### 49. How to print all the values of an array?

In [ ]:
# prompt: How to print all the values of an array?

import numpy as np

# Create a 5x5 array
array = np.arange(25).reshape(5, 5)

# Print all the values of the array
print(array.flatten())


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


#### 50. How to find the closest value (to a given scalar) in a vector?

In [ ]:
# prompt: How to find the closest value (to a given scalar) in a vector?

import numpy as np

def find_closest_value(vector, scalar):
  """
  Finds the closest value to a given scalar in a vector.

  Args:
      vector: The vector to search.
      scalar: The scalar value to find the closest value to.

  Returns:
      The closest value in the vector to the scalar.
  """

  # Calculate the absolute differences between the scalar and each element in the vector
  differences = np.abs(vector - scalar)

  # Find the index of the element with the smallest absolute difference
  closest_index = np.argmin(differences)

  # Return the closest value
  return vector[closest_index]

# Example usage
vector = np.array([1.1, 1.5, 1.8, 2.2, 2.5])
scalar = 1.7

closest_value = find_closest_value(vector, scalar)

print(f"Closest value to {scalar} in the vector is: {closest_value}")


Closest value to 1.7 in the vector is: 1.8


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b)

In [ ]:
# prompt: Create a structured array representing a position (x,y) and a color (r,g,b)

color = np.dtype([('r', np.ubyte, 1),
                  ('g', np.ubyte, 1),
                  ('b', np.ubyte, 1)])

position = np.dtype([('x', np.float64, 1),
                  ('y', np.float64, 1)])

structured_array = np.zeros((10, 1), dtype=[('position', position), ('color', color)])



#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances

In [ ]:
# prompt: Consider a random vector with shape (100,2) representing coordinates, find point by point distances

import numpy as np

# Generate a random vector with shape (100,2) representing coordinates
coordinates = np.random.rand(100, 2)

# Calculate the pairwise distances between all points
distances = np.sqrt(np.sum((coordinates[:, np.newaxis, :] - coordinates[np.newaxis, :, :])**2, axis=-1))

# Print the point by point distances
print(distances)


[[0.         0.57548925 0.42176535 ... 0.81826563 0.52152182 0.53129956]
 [0.57548925 0.         0.51128198 ... 0.40791735 0.25578813 0.31917923]
 [0.42176535 0.51128198 0.         ... 0.90047293 0.28404579 0.69284733]
 ...
 [0.81826563 0.40791735 0.90047293 ... 0.         0.6634024  0.29405823]
 [0.52152182 0.25578813 0.28404579 ... 0.6634024  0.         0.52328674]
 [0.53129956 0.31917923 0.69284733 ... 0.29405823 0.52328674 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
# prompt: How to convert a float (32 bits) array into an integer (32 bits) in place?

x = np.array([1.1, 2.2, 3.3, 4.4], dtype=np.float32)
np.trunc(x, out=x)
print(x)


[1. 2. 3. 4.]


#### 54. How to read the following file?
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
# prompt: How to read the following file?
# 1, 2, 3, 4, 5
# 6,  ,  , 7, 8
#  ,  , 9,10,11

import numpy as np

# Read the file with missing values as NaN
data = np.genfromtxt('data.txt', delimiter=',', missing_values=' ')

# Print the data
print(data)


FileNotFoundError: data.txt not found.

#### 55. What is the equivalent of enumerate for numpy arrays?

In [ ]:
# prompt: What is the equivalent of enumerate for numpy arrays?

for i, element in np.ndenumerate(array):
    # Do something with the element and its index
    print(f"Index: {i}, Element: {element}")


Index: (0, 0), Element: 0
Index: (0, 1), Element: 1
Index: (0, 2), Element: 2
Index: (0, 3), Element: 3
Index: (0, 4), Element: 4
Index: (1, 0), Element: 5
Index: (1, 1), Element: 6
Index: (1, 2), Element: 7
Index: (1, 3), Element: 8
Index: (1, 4), Element: 9
Index: (2, 0), Element: 10
Index: (2, 1), Element: 11
Index: (2, 2), Element: 12
Index: (2, 3), Element: 13
Index: (2, 4), Element: 14
Index: (3, 0), Element: 15
Index: (3, 1), Element: 16
Index: (3, 2), Element: 17
Index: (3, 3), Element: 18
Index: (3, 4), Element: 19
Index: (4, 0), Element: 20
Index: (4, 1), Element: 21
Index: (4, 2), Element: 22
Index: (4, 3), Element: 23
Index: (4, 4), Element: 24


#### 56. Generate a generic 2D Gaussian-like array

In [ ]:
# prompt: Generate a generic 2D Gaussian-like array

import numpy as np

def gaussian_2d(shape, sigma=1):
    """
    Creates a 2D Gaussian-like array with the given shape and sigma.

    Args:
        shape: The shape of the array.
        sigma: The standard deviation of the Gaussian.

    Returns:
        A 2D Gaussian-like array.
    """

    # Create a grid of coordinates
    x = np.linspace(-3*sigma, 3*sigma, shape[0])
    y = np.linspace(-3*sigma, 3*sigma, shape[1])
    xv, yv = np.meshgrid(x, y)

    # Calculate the Gaussian function
    z = np.exp(-((xv**2 + yv**2) / (2*sigma**2)))

    return z


#### 57. How to randomly place p elements in a 2D array?

In [ ]:
# prompt: How to randomly place p elements in a 2D array?

def place_elements(array, p):
  """
  Randomly places p elements in a 2D array.

  Args:
      array: The 2D array.
      p: The number of elements to place.

  Returns:
      The array with the elements placed randomly.
  """

  # Get the shape of the array
  rows, cols = array.shape

  # Generate random coordinates
  coordinates = np.random.randint(0, rows * cols, p)

  # Place the elements at the random coordinates
  array.flat[coordinates] = 1

  return array

# Create a 5x5 array
array = np.zeros((5, 5))

# Place 10 elements randomly
array = place_elements(array, 10)

# Print the array
print(array)


[[0. 1. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 1.]
 [1. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]]


#### 58. Subtract the mean of each row of a matrix

In [ ]:
# prompt:  Subtract the mean of each row of a matrix

def subtract_row_means(matrix):
  """
  Subtracts the mean of each row from the matrix.

  Args:
      matrix: The matrix to process.

  Returns:
      The matrix with the row means subtracted.
  """

  # Calculate the mean of each row
  row_means = np.mean(matrix, axis=1)

  # Subtract the row means from the matrix
  return matrix - row_means[:, np.newaxis]

# Create a random matrix
matrix = np.random.rand(5, 5)

# Subtract the mean of each row
matrix = subtract_row_means(matrix)

# Print the matrix
print(matrix)


[[-0.198626    0.43003437 -0.15667698 -0.18502094  0.11028956]
 [-0.25496744 -0.50764454  0.25276149  0.21654847  0.29330202]
 [ 0.07574514 -0.42910757  0.13375266  0.03770177  0.18190801]
 [ 0.02622579  0.23836467 -0.19374397 -0.15276906  0.08192257]
 [ 0.01760526  0.31129142 -0.12306845  0.05998611 -0.26581435]]


#### 59. How to sort an array by the nth column?

In [ ]:
# prompt: How to sort an array by the nth column?

def sort_by_column(array, n):
  """
  Sorts an array by the nth column.

  Args:
      array: The array to sort.
      n: The column to sort by.

  Returns:
      The sorted array.
  """

  # Get the nth column of the array
  column = array[:, n]

  # Sort the array by the nth column
  sorted_array = array[np.argsort(column)]

  return sorted_array

# Create a random array
array = np.random.rand(5, 5)

# Sort the array by the 3rd column
sorted_array = sort_by_column(array, 2)

# Print the sorted array
print(sorted_array)


[[0.29877561 0.98941132 0.59974823 0.74077917 0.10385356]
 [0.50069972 0.7959151  0.60707952 0.43436269 0.42096417]
 [0.79021847 0.66174453 0.68269125 0.41360074 0.44376081]
 [0.45578278 0.85329523 0.69711002 0.9489077  0.97524606]
 [0.84085422 0.85943314 0.70042335 0.06987223 0.12975137]]


#### 60. How to tell if a given 2D array has null columns?

In [ ]:
# prompt: How to tell if a given 2D array has null columns?

def has_null_columns(array):
  """
  Checks if a given 2D array has null columns.

  Args:
      array: The 2D array to check.

  Returns:
      True if the array has null columns, False otherwise.
  """

  # Check if any of the columns are all NaN
  return np.any(np.isnan(array).all(axis=0))

# Create a random array
array = np.random.rand(5, 5)

# Set one of the columns to NaN
array[:, 2] = np.nan

# Check if the array has null columns
has_null_columns = has_null_columns(array)

# Print the result
print(f"The array has null columns: {has_null_columns}")


The array has null columns: True


#### 61. Find the nearest value from a given value in an array

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

#### 63. Create an array class that has a name attribute

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once?

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices?

#### 69. How to get the diagonal of a dot product?

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?

#### 72. How to swap two rows of an array?

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?

#### 75. How to compute averages using a sliding window over an array?

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])

#### 77. How to negate a boolean, or to change the sign of a float inplace?

In [ ]:
# prompt: How to negate a boolean, or to change the sign of a float inplace?

# Negate a boolean
a = True
print(np.logical_not(a))  # Output: False

# Change the sign of a float inplace
b = -1.2
np.negative(b, out=b)
print(b)  # Output: 1.2


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i]

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

#### 88. How to implement the Game of Life using numpy arrays?

#### 89. How to get the n largest values of an array

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item)

#### 91. How to create a record array from a regular array?

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])

#### 95. Convert a vector of ints into a matrix binary representation

#### 96. Given a two dimensional array, how to extract unique rows?

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).